---
- name: Create RoundCube config volume
  docker_volume:
    name: "{{ roundcubemail_config_volume_name }}"

#- name: Create RoundCube logs volume
#  docker_volume:
#    name: "{{ roundcubemail_logs_volume_name }}"

- name: Pull docker container/tag
  docker_image:
    name: "{{ roundcubemail_container_image }}"
    tag: "{{ roundcubemail_container_tag }}"
    pull: "yes"

- name: Create a docker container
  docker_container:
    name: "{{ roundcubemail_container_name }}"
    image: "{{ roundcubemail_container_image }}:{{ roundcubemail_container_tag }}"
    volumes:
        - "{{ roundcubemail_config_volume_name }}:/var/roundcube/config"
        - "{{ roundcubemail_logs_volume_name }}:/var/log/apache2"
    restart_policy: "{{ roundcubemail_restart_policy | default(omit) }}"
    published_ports: "{{ roundcubemail_published_ports | default(omit) }}"
    privileged: "{{ roundcubemail_privileged | default(omit) }}"
    hostname: "{{ roundcubemail_hostname | default(omit) }}"
    env: "{{ roundcubemail_env }}"

# This doesn't work because the "logs files" are symlinks to /dev/std[out,err]
#- name: Link container logs to LFS compliant location
#  file:
#    src: "/var/lib/docker/volumes/{{ roundcubemail_logs_volume_name }}/_data/"
#    dest: "/var/log/roundcube"
#    state: "link"
